buildscript {
    repositories {
        jcenter()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'

def libVersionCode = Integer.parseInt(project.VERSION_CODE)
def libVersionName = project.VERSION_NAME

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode libVersionCode
        versionName libVersionName
    }

    testOptions.unitTests.includeAndroidResources = true
}

dependencies {
    testImplementation rootProject.ext.junit
    testImplementation rootProject.ext.roboelectric

    implementation rootProject.ext.androidxAppCompat
    implementation project(':conductor')
    implementation 'androidx.viewpager2:viewpager2:1.0.0'
}

apply from: rootProject.file('dependencies.gradle')
